language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc

    - os: osx
      compiler: gcc

    - os: linux
      compiler: clang

    - os: osx
      compiler: clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make test
